# Generated by Django 5.1.2 on 2024-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovieStore', '0002_pelicula_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='foto',
            field=models.ImageField(default=0.0006288178224937119, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
