# Generated by Django 5.1.2 on 2024-11-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovieStore', '0003_genero_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(default=0.0006288178224937119, help_text='Duración en minutos'),
            preserve_default=False,
        ),
    ]
