# Generated by Django 5.1.2 on 2024-11-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovieStore', '0004_pelicula_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
    ]
