# Generated by Django 5.1.2 on 2024-11-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMovieStore', '0006_genero_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
    ]
